### ISSUE TITLE
New command: add X to delete and Shift X to delete without confirmation

### ISSUE THREAD

**Issue by NathanLovato** [imjp94/gd-blender-3d-shortcuts#11]
As in Blender, just to not have to reach for Del/Suppr. and make the workflow slightly faster. The addon could provide this to not have to remap the built-in shortcut.

Happy to contribute this if it's desired.

**Comment by imjp94** [comment]
Sounds good to me, feel free to open PR.

Thank you!

**Comment by NathanLovato** [comment]
Will do! I have a busy schedule this week but I'll try to find some spare time to add this and other suggested features :)
