### ISSUE TITLE
Nested resources don't work anymore

### ISSUE THREAD

**Issue by rakinishraq** [imjp94/gd-blender-3d-shortcuts#21]
I'm running Godot 4.2 beta 1 mono on Windows 11.

While having this plugin enabled, i cant expand a new spatial material in a mesh in a meshinstance node anymore. when i click it, I keep getting this message.

ERROR: Condition "plugins_list.has(p_plugin)" is true.
   at: add_plugin (editor/editor_node.cpp:8112)

I also couldn't open an InputEventKey in an Array in a Shortcut menu to configure the bindings for the NoctemCat/BottomPanelShortcuts plugin so I know that it's not a one-off, either. I tried the master and godot4 branches and both did the same thing, unfortunately.

**Comment by tpan496** [comment]
+1 same issue here

**Comment by TheBricktop** [comment]
Same issue, tried downloading master to check if it fixes it but it doesnt.
Godot 4.1.3

**Comment by dc1248** [comment]
Interesting. I remember seeing that error but I didn't connect it to this plugin (which I haven't been using in 4.2). This plugin does some tricky stuff with input handling, which could definitely be the root of this problem, but this error makes me wonder if it's something stranger.

Where does that error come from? EditorPluginList::add_plugin()
https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/editor/editor_node.cpp#L8202
Does that mean Godot is trying to re-add the plugin every time you see that error? Baffling.

**Comment by imjp94** [comment]
Fixed in #28
