### ISSUE TITLE
Add shift+d to duplicate

### ISSUE THREAD

**Issue by SirLich** [imjp94/gd-blender-3d-shortcuts#7]
This is another one I use a lot in blender for whiteboxing. Any possibility this could be added?

**Comment by imjp94** [comment]
Duplicate is supported in Godot, which is `Ctrl+D` by default. You can simply change it to `Shift+D`

![Screenshot 2022-02-21 095123](https://user-images.githubusercontent.com/11486079/154876120-1693ab7c-1c45-41d4-9907-6356823e23e3.png)
